services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: ex2-backend
    env_file:
      - docker/backend.env
    ports:
      - "${LOCALHOST_BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - sqlite_data:/data

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: ex2-frontend
    env_file:
      - docker/frontend.env
    ports:
      - "${LOCALHOST_FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend

volumes:
  sqlite_data: