services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: ex1-backend
    env_file:
      - docker/backend.env
    ports:
      - "${LOCALHOST_BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: ex1-frontend
    env_file:
      - docker/frontend.env
    ports:
      - "${LOCALHOST_FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend